// tokens.css: the component framework's theme, emitted as CSS custom
// properties so the site and the widgets it documents share one source
// (packages/components/src/theme.ts). Light is the default, dark follows the
// OS preference, and data-theme on the root forces either; site.css consumes
// the tokens.
//
// Naming: --srt-<category>-<kebab-token>; color tokens drop the category
// (--srt-primary, --srt-text-muted). Numbers are logical px except line
// heights and font weights, which are unitless as in the theme. The font
// family is a core stack name ("sans"), not a CSS family, so it is not emitted.
import { darkTheme, lightTheme, type Theme } from "@solidrt/components/theme";

function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());
}

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((l) => "  " + l + ";").join("\n")}\n}\n`;
}

function colorLines(theme: Theme): string[] {
  return Object.entries(theme.color).map(([k, v]) => `--srt-${kebab(k)}: ${v}`);
}

// Scheme-independent tokens; both presets share them, so read from one.
function sharedLines(theme: Theme): string[] {
  let out: string[] = [];
  for (let [k, v] of Object.entries(theme.spacing)) out.push(`--srt-spacing-${k}: ${v}px`);
  for (let [k, v] of Object.entries(theme.radius)) out.push(`--srt-radius-${k}: ${v}px`);
  for (let [k, v] of Object.entries(theme.borderWidth)) out.push(`--srt-border-width-${k}: ${v}px`);
  for (let role of ["caption", "label", "body", "title", "heading"] as const) {
    let t = theme.text[role];
    out.push(`--srt-${role}-size: ${t.size}px`);
    out.push(`--srt-${role}-line-height: ${t.lineHeight}`);
    out.push(`--srt-${role}-weight: ${t.weight}`);
  }
  return out;
}

export function tokensCss(): string {
  return [
    "/* Generated by website/src/tokens.ts from packages/components/src/theme.ts. Do not edit. */\n",
    block(":root", sharedLines(lightTheme)),
    block(":root, [data-theme=light]", colorLines(lightTheme)),
    "@media (prefers-color-scheme: dark) {\n" +
      block(":root:not([data-theme=light])", colorLines(darkTheme)).replace(/^/gm, "  ").trimEnd() +
      "\n}\n",
    block("[data-theme=dark]", colorLines(darkTheme)),
  ].join("\n");
}