export let mappings = {
  display: {
    block: 0,
    flex: 1,
    grid: 2,
    none: 3,
  },
  flexDirection: {
    row: 0,
    column: 1,
    "row-reverse": 2,
    "column-reverse": 3,
  },
  flexWrap: {
    nowrap: 0,
    wrap: 1,
    "wrap-reverse": 2,
  },
  alignItems: {
    start: 0,
    end: 1,
    "flex-start": 2,
    "flex-end": 3,
    center: 4,
    baseline: 5,
    stretch: 6,
  },
  alignSelf: {
    start: 0,
    end: 1,
    "flex-start": 2,
    "flex-end": 3,
    center: 4,
    baseline: 5,
    stretch: 6,
  },
  alignContent: {
    start: 0,
    end: 1,
    "flex-start": 2,
    "flex-end": 3,
    center: 4,
    stretch: 5,
    "space-between": 6,
    "space-evenly": 7,
    "space-around": 8,
  },
  justifyContent: {
    start: 0,
    end: 1,
    "flex-start": 2,
    "flex-end": 3,
    center: 4,
    stretch: 5,
    "space-between": 6,
    "space-evenly": 7,
    "space-around": 8,
  },
  gridAutoFlow: {
    row: 0,
    column: 1,
    "row-dense": 2,
    "column-dense": 3,
  },
  drawStyle: {
    fill: 0,
    stroke: 1,
    "stroke-and-fill": 2,
  },
  strokeCap: {
    butt: 0,
    round: 1,
    square: 2,
  },
  strokeJoin: {
    miter: 0,
    round: 1,
    bevel: 2,
  },
  blendMode: {
    clear: 0,
    source: 1,
    destination: 2,
    "source-over": 3,
    "destination-over": 4,
    "source-in": 5,
    "destination-in": 6,
    "source-out": 7,
    "destination-out": 8,
    "source-atop": 9,
    "destination-atop": 10,
    xor: 11,
    plus: 12,
    modulate: 13,
    screen: 14,
    overlay: 15,
    darken: 16,
    lighten: 17,
    "color-dodge": 18,
    "color-burn": 19,
    "hard-light": 20,
    "soft-light": 21,
    difference: 22,
    exclusion: 23,
    multiply: 24,
    hue: 25,
    saturation: 26,
    color: 27,
    luminosity: 28,
  },
  fontStyle: {
    normal: 0,
    italic: 1,
  },
  textAlign: {
    left: 0,
    right: 1,
    center: 2,
    justify: 3,
  },
  position: {
    relative: 0,
    absolute: 1,
  },
  overflow: {
    visible: 0,
    clip: 1,
    hidden: 2,
    scroll: 3,
  },
  pointerEvents: {
    auto: 0,
    none: 1,
    all: 2,
  },
  fillRule: {
    nonZero: 0,
    evenOdd: 1,
  },
}
