use rquickjs::{Ctx, JsLifetime};
use std::sync::Arc;

/// Log level passed to the logger callback.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogLevel {
  Debug,
  Log,
  Warn,
  Error,
}

/// Shared log sink, stored as userdata in the JS context.
#[derive(Clone, JsLifetime)]
pub struct Logger(#[qjs(skip_trace)] pub(crate) Arc<dyn Fn(LogLevel, &str) + Send + Sync>);

impl Logger {
  pub fn debug(&self, msg: &str) {
    (self.0)(LogLevel::Debug, msg);
  }

  pub fn log(&self, msg: &str) {
    (self.0)(LogLevel::Log, msg);
  }

  pub fn warn(&self, msg: &str) {
    (self.0)(LogLevel::Warn, msg);
  }

  pub fn error(&self, msg: &str) {
    (self.0)(LogLevel::Error, msg);
  }
}

pub fn default_logger() -> Logger {
  Logger(Arc::new(|level, msg| match level {
    LogLevel::Debug => log::debug!("{msg}"),
    LogLevel::Log => log::info!("{msg}"),
    LogLevel::Warn => log::warn!("{msg}"),
    LogLevel::Error => log::error!("{msg}"),
  }))
}

pub trait CtxLogger {
  fn logger(&self) -> Logger;
}

impl CtxLogger for Ctx<'_> {
  fn logger(&self) -> Logger {
    self.userdata::<Logger>().unwrap().clone()
  }
}

/// Formats a `rquickjs::Error` for display. When it is a pending JS exception,
/// clears it from the context and returns the exception message and stack;
/// otherwise returns the Rust error string.
pub fn format_js_error(ctx: &Ctx<'_>, err: rquickjs::Error) -> String {
  if err.is_exception() {
    let caught = ctx.catch();
    caught.as_exception().map_or_else(|| format!("{caught:?}"), |e| e.to_string())
  } else {
    err.to_string()
  }
}

/// Reports an error from invoking a JS callback (event listener, timer, etc.)
/// to the logger. When the error is a thrown JS exception, the pending
/// exception is retrieved from the context with `ctx.catch()` so the message
/// and stack are surfaced instead of a bare "Exception generated by QuickJS".
/// Use this anywhere a JS callback is called fire-and-forget, so throws are
/// not silently swallowed.
pub fn report_uncaught(ctx: &Ctx<'_>, err: rquickjs::Error, context: &str) {
  let msg = format_js_error(ctx, err);
  ctx.logger().error(&format!("[flux] uncaught exception in {context}: {msg}"));
}

/// Logging function type: receives a log level and message string.
pub type LogFn = Box<dyn Fn(LogLevel, &str) + Send + Sync>;
