#!/usr/bin/env bun
//
// Generate okf/index.md from the frontmatter of every working note.
//
// A hand-maintained index is a lie with a delay: it is correct on the day it is
// written and drifts every time a file moves. This one is generated, and
// --check fails if it has drifted, so it cannot be wrong for longer than one CI
// run.
//
// One rule is enforced here rather than left to discipline: every file carries
// title, description and created. Missing frontmatter is not a formatting nit -
// the index shows the description and nothing else, so a file without one is
// invisible.
//
// State lives in the directory, never in a status field: things move by git mv,
// so there is deliberately no status to parse and nothing here can disagree
// with what `ls` shows. upstream/ is the single exception, because the state it
// tracks belongs to the dependency and no move of ours expresses it. See
// okf/README.md.

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

let REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
let OKF = join(REPO, "okf");
let INDEX = join(OKF, "index.md");
let WIDTH = 78;

// Order matters: this is the order of the generated index, and it reads as the
// life of a document - active, queued, finished, learned - with upstream, which
// has no lifecycle of ours, at the end.
let SECTIONS = [
  ["plans", "Plans", "Decided and being worked on now. A plan nobody is working on goes back to backlog/ - see okf/README.md."],
  ["backlog", "Backlog", "Shaped, not started."],
  ["done", "Done", "Finished, kept for the reasoning."],
  ["notes", "Notes", "Knowledge. No lifecycle - true or wrong, not open or closed."],
  ["upstream", "Upstream", "Bugs in our dependencies. Status here is the dependency's, not ours."],
];

let REQUIRED = ["title", "description", "created"];

// Flat key: value only, one line each. A parser that cannot express nesting
// keeps the frontmatter flat by design.
function frontmatter(path: string): Record<string, string> {
  let lines = readFileSync(path, "utf8").split("\n");
  if (lines[0]?.trim() !== "---") return {};
  let fields: Record<string, string> = {};
  for (let line of lines.slice(1)) {
    if (line.trim() === "---") break;
    let colon = line.indexOf(":");
    if (colon > 0 && !line.startsWith(" ")) {
      fields[line.slice(0, colon).trim()] = line.slice(colon + 1).trim();
    }
  }
  return fields;
}

function notes(directory: string): string[] {
  let dir = join(OKF, directory);
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((f) => f.endsWith(".md")).sort();
}

function wrap(text: string, indent: string): string[] {
  let out: string[] = [];
  let line = indent;
  for (let word of text.split(/\s+/).filter(Boolean)) {
    if (line !== indent && line.length + word.length + 1 > WIDTH) {
      out.push(line);
      line = indent;
    }
    line += (line === indent ? "" : " ") + word;
  }
  out.push(line);
  return out;
}

function render(): string {
  let out = [
    "---",
    "title: Index",
    "description: Generated by scripts/build-okf-index.ts. Do not hand-edit.",
    "---",
    "",
    "# okf",
    "",
    "Generated from frontmatter by `scripts/build-okf-index.ts`. The conventions",
    "are in [README.md](README.md); loose ideas are in [ideas.md](ideas.md).",
  ];

  for (let [directory, heading, blurb] of SECTIONS) {
    let files = notes(directory);
    out.push("", `## ${heading}`, "", blurb, "");
    if (files.length === 0) {
      out.push("_(empty)_");
      continue;
    }
    for (let file of files) {
      let fields = frontmatter(join(OKF, directory, file));
      let title = fields.title ?? file.replace(/\.md$/, "");
      let when = fields.completed ?? fields.created ?? "";
      out.push(`- **[${title}](${directory}/${file})**${when ? ` [${when}]` : ""}`);
      out.push(...wrap(fields.description ?? "", "  "));
    }
  }
  return out.join("\n") + "\n";
}

function problems(): string[] {
  let found: string[] = [];
  for (let [directory] of SECTIONS) {
    for (let file of notes(directory)) {
      let fields = frontmatter(join(OKF, directory, file));
      let missing = REQUIRED.filter((key) => !(key in fields));
      if (missing.length > 0) {
        found.push(`${directory}/${file}: no ${missing.join(", ")}`);
      }
      if ("status" in fields && directory !== "upstream") {
        found.push(`${directory}/${file}: has a status field. State is the directory - move the file instead.`);
      }
    }
  }
  return found;
}

let check = process.argv.includes("--check");
let found = problems();
let content = render();

if (check) {
  let current = existsSync(INDEX) ? readFileSync(INDEX, "utf8") : "";
  if (current !== content) {
    found.push("index.md is stale - run bun scripts/build-okf-index.ts");
  }
  for (let problem of found) console.log(`  ${problem}`);
  if (found.length > 0) {
    console.log(`\nFailed: ${found.length} problem(s) in okf/.`);
    process.exit(1);
  }
  console.log("okf index current: okf/index.md");
  process.exit(0);
}

for (let problem of found) console.log(`  ${problem}`);
writeFileSync(INDEX, content);
let counts = SECTIONS.map(([d]) => `${notes(d).length} ${d}`).join(", ");
console.log(`-> okf/index.md (${counts})`);
process.exit(found.length > 0 ? 1 : 0);
